# Vektörleştirme 
<img align="right" src="./image/Vectors.PNG" style="width:340px;" > Vektörler sıralı sayı dizileridir. Bir vektörün elemanları tamamen aynı türde olmalıdır. Örneğin bir vektörün elemanları arasında hem sayılar hem de metinsel ifadeler yer alamaz. Bir vektörün (dizi) eleman sayısı boyut olarak adlandırılır.  Gösterilen vektörün bir boyutu 𝑛’dir. Bir vektörün elemanları bir indeksle referans alınabilir. Matematik ortamlarında indeksler genellikle 1’den n’e kadar gider. Bilgisayar bilimlerinde ve bu laboratuvarlarda, indeksleme genellikle 0’dan n-1’e kadar gider. Notasyonda, bir vektörün elemanları, bireysel olarak referans alındığında, alt simge ile indeksi gösterecektir; örneğin, vektör 𝐱’in 0𝑡ℎ elemanı 𝑥0’dır. 

## Neden Vektörleştirme ?
Vektörleştirmenin kullanılmasının sebebi biraz sonra kodlara dikkat ettiğinizde fark edeceğiniz gibi zamandan tasarruf etmektir. Bunu yaparken kendi kodumuzun çalışama zamanı ile NumPy kütüphanesinde bulunan hazır kodların çalışma zamanını kıyaslayacağız.

## Vektör Oluşturma

In [1]:
import numpy as np

a = np.zeros(5);                print(f"np.zeros(5) :               a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros((4,)) :            a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.arange(4);               print(f"np.arange(4):               a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4):          a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5,4,3,2]);        print(f"np.array([5,4,3,2]):        a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]);       print(f"np.array([5.,4,3,2]):       a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(5) :               a = [0. 0. 0. 0. 0.], a shape = (5,), a data type = float64
np.zeros((4,)) :            a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.24573868 0.84230215 0.85198302 0.17073177], a shape = (4,), a data type = float64
np.arange(4):               a = [0 1 2 3], a shape = (4,), a data type = int32
np.random.rand(4):          a = [0.15505291 0.62524166 0.77630223 0.27930901], a shape = (4,), a data type = float64
np.array([5,4,3,2]):        a = [5 4 3 2], a shape = (4,), a data type = int32
np.array([5.,4,3,2]):       a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


Bir vektörde bulunan elemanı çağırırken vektörürn boyutu göz önünde bulundurulmalıdır. Aksi taktirde elemanı çağırmak için girmiş olduğunuz index değerine ait bir eleman bulunmayabilir.

In [2]:
a = np.arange(10)
print(a)
print(f"a[5].shape: {a[5].shape} a[5]  = {a[5]}")
print(f"a[-2] = {a[-2]}")

try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[5].shape: () a[5]  = 5
a[-2] = 8
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


Vektörler de bulunan belirli index aralığındaki elemanları çağırarak işlem yapabilmekteyiz.

In [3]:
a = np.arange(10)
print(f"a        =  {a}")
c = a[2:7:1];     print("a[2:7:1] = ", c)
c = a[2:7:2];     print("a[2:7:2] = ", c)
c = a[3:];        print("a[3:]    = ", c)
c = a[:3];        print("a[:3]    = ", c)
c = a[:];         print("a[:]     = ", c)

a        =  [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


Vektörlerle çeşitli matematiksel işlemler dahilinde hesaplamalar yapılabilmektedir.

In [4]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
b = -a 
print(f"b = -a        : {b}")
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")
b = np.mean(a)
print(f"b = np.mean(a): {b}")
b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


İki vektörün skaler toplamı için vektörlerin boyutunun aynı olması gerekmektedir.

In [5]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

Binary operators work element wise: [0 0 6 8]
The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


Bir vektörle bir sayının skaler çarpımıda mümkündür.

In [6]:
a = np.array([1, 2, 3, 4])
b = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


İki vektör arasında vektörel çarpım yapmakta mümkündür. Ve toplama işleminde olduğu gibi tüm vektörel işlemler için vektörlerin boyutları aynı olmalıdır. (Tek boyutlu vektörler... Matrislerler ve Tensörler hariçtir.) $ x= \sum(a^ib^i) $
<img src="./image/dot_notrans.gif" width=800>

In [7]:
def my_dot(a,b):
    x = 0
    for i in range(a.shape[0]): 
        x += a[i] * b[i]
    return x   

In [8]:
a = np.array([1,2,3,4])
b = np.array([-1,-2, 3, 4])
print(f"my_dot(a,b) = {my_dot(a,b)}")

my_dot(a,b) = 20


NumPy kütüphanesinin hazır kodlarından biri olana  ve yukarıda yazdığımız fonksiyonu oluşturmamıza lüzüm bırakmayan `np.dot` ifadesi bulunmaktadır. Bu yukarıda yazmış olduğumuz fonksiyon ile birebir aynı işlevi gerçekleştirir. Fakat NumPy kütüphanesinin ayrıcalıklı tarafı bu ifade kullanıldığı takdirde cihaz donanımı daha optimize bir biçimde kullanılmış ve zamandan tasarruf edilicektir. NumPy kütüphanesinin bu özelliğe sahip olmasını sağlayan şey her ifadenin biraz önce bizim yazmış olduğumuz gibi yalnızca işlem odaklı değil aynı zamanda cihaz özelliklerinin optimize bir biçimde kullanılarak daha verimli ve hızlı sonuç almamızı sağlayan kodlar bütününden oluşmasıdır.

In [9]:
a = np.array([1,2,3,4])
b = np.array([-1,-2, 3, 4])
c = np.dot(a,b)
print(f"c = {c}")

c = 20


Bu kadar az sayıda veriye sahip olan vektörlerle işlem yapıldığında elbette bizim yazmış olduğumuz fonksiyon ile NumPy kütüphanesinin ifadesin sonuç verme hızı arasındaki fark kayda değer ölçekte olmayacaktır. Ancak bu elemanların sayısının yüksek oldukları vektörler ile işlem yapılırken ;

In [10]:
import time

np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 43.3104 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 2410.7935 ms 


Görmüş olduğunuz gibi iki fonksiyon arasındaki hesaplama bu örnek için hızı 5 kattan fazla bulunmakta.

## Matrisler
Matrisler, iki boyutlu dizilerdir. Bir matrisin elemanları aynı türdedir.m genellikle satır sayısını, n ise sütun sayısını ifade ederBir matrisin elemanlarına iki boyutlu bir indeksle erişilebilir. Matematiksel bağlamlarda indeks numaraları genellikle 1'den n'e kadar giderken, bilgisayar biliminde0'dan n-1'e kadar olacaktır.<center> <img src="./image/Matrices.PNG"  alt='missing'  width=900><center/>

### Matris Oluşturma

In [11]:
import numpy as np
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     
a = np.zeros((2, 1))                                                 
print(f"a shape = {a.shape}, a = {a}") 
a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 
a = np.array([[5], [4], [3]]);   print(f"a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5], 
              [4],   
              [3]]); print(f"a shape = {a.shape}, np.array: a = {a}")

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.44236513]]
a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


### Matrislerle İşlemler

In [12]:
a = np.arange(6).reshape(-1, 2)
print(f"a.shape: {a.shape}, \na= {a}")
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int32'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


In [13]:
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
